### PR TITLE
npm audit fix

### PR DESCRIPTION
**Pull request by ryanwi**
Patches security vulnerabilities

### CODE REVIEW

**Review by saralohr — APPROVED** [review]
Thank you! 🙌

**Review by bradcypert — APPROVED** [review]

**Review by bradcypert — COMMENTED** [review]
why did this one go backwards? O.o

**Comment by ryanwi** [comment]
> Do we want to cut a build for this right away or can we roll these changes up into the next one?

@bradcypert what's all involved in cutting a a build? If you think one is coming up, I am fine with rolling these changes up.

> why did the gulp dependency go backwards? O.o

Not sure about that, I was mostly letting `npm` do the work. Will check it out.

**Comment by ryanwi** [comment]
> why did the gulp dependency go backwards? O.o

Ah, looks like the --force did it. I can remove that if it's breaking things. Which begs the question, how do I know if this breaks anything?

**Comment by bradcypert** [comment]
@ryanwi Our CI currently just ensures that things build, but we also can check the storybook to ensure that our components still work `yarn storybook` should get you there :)

**Comment by bradcypert** [comment]
FWIW: I think Gulp is only used for the CSS pipeline, so as long as the build succeeds, I think it should be fine.

**Comment by ryanwi** [comment]
The results of `npm audit` do not change from the master branch to this branch after running audit fix, so I am removing those changes from the PR and just patching the one vulnerability with object-path.

**Comment by bradcypert** [comment]
@ryanwi thanks! I'll get those bundled into a release soon!

**Pull request merged**
