### PR TITLE
add netlify config with cors headers

### PR DESCRIPTION
**Pull request by bradjteamsnap**
### Description
This is a fix for CORS errors showing up for fonts when importing teamsnap-ui scss.

### Screenshots
Screen Shot 2021-07-20 at 12 48 37 PM

### CODE REVIEW

**Comment by ryanwi** [comment]
Are the errors on .teamsnap.com sites? Can we open it up slightly without allowing all origins?  I’m trying to understand what the error is telling us, protecting us from.

**Comment by bradjteamsnap** [comment]
> Are the errors on .teamsnap.com sites?

Yes, on accounts.teamsnap.com after updating to the post-dugout version. Was thinking about a wildcard subdomain for '*.teamsnap.com' but is this npm package technically open source?

**Comment by ryanwi** [comment]
> is this npm package technically open source?

Yeah, I think so, it could be pulled into any club customer site right?

**Review by ryanwi — APPROVED** [review]

**Review by bradcypert — APPROVED** [review]
Great find and great work on this!

**Pull request merged**
