### PR TITLE
Upgrade and tweak scss compliation 

### PR DESCRIPTION
**Pull request by l3aconator**
**Context**: When building the marketing site, our build tool fires off tons of deprecation notices per the following article: https://sass-lang.com/documentation/breaking-changes/slash-div

- Remove `node-sass` for latest `sass`
    - Node Sass and libsass are deprecated: https://sass-lang.com/blog/libsass-is-deprecated
The preferred package to use now is dart-sass (sass).
- Upgrade `sass-loader` to `10.2.0` <- this is the latest version we can go to given storybook
   - This was necessary to pick up the updated `scss` syntax
- Run migration tool on the deprecated `scss` syntax
- Upgrade `gulp-sass` 

This PR needs a good amount of scrutiny and I will need help releasing to `npm`.

### CODE REVIEW

**Review by saralohr — APPROVED** [review]
This looks good to me! Happy to help with NPM deploy or we can get you added if you'd rather self-serve.

**Review by bradjteamsnap — APPROVED** [review]
looks good to me as well, tried building the brach locally just to be sure 👍

**Comment by l3aconator** [comment]
@saralohr I would love your help with the NPM deploy whenever you get a chance :)

**Comment by saralohr** [comment]
Sure @l3aconator I'll merge this and deploy to NPM.

**Pull request merged**
