### PR TITLE
Add linter

### PR DESCRIPTION
**Pull request by BillyFigueroa**
Adding linter for v4 so that our code base can have a more uniform coding style

This addresses and fixes issue #691

### CODE REVIEW

**Review by jondauz — APPROVED** [review]
Looks good to me.

**Review by bradjteamsnap — APPROVED** [review]
Nice!

**Comment by BillyFigueroa** [comment]
> Nice! 

Going to be adding a git pre hook with husky soon maybe in a diff pull request.

**Review by bradcypert — APPROVED** [review]
Can we add a section in the README under linters about our use of eslint?

**Comment by bradcypert** [comment]
@BillyFigueroa worth mentioning that precommit hook will be clientside only and I dont think it gets committed with the repo. I was experimenting with this a while back to prevent direct commits to specific branches with another repo and ended up adding a folder called hooks with the precommit hook there, and then adding a makefile that set up the hooks for people. That being said, people have to opt into it, which is fine, but I wouldn't assume everyone will use it.

On that note, I probably won't. I'm a regularly committer (hence my favor of squashing commits 😃). If I have to wait for a  lint everytime I commit, that'll likely slow me down tremendously, haha. I will still adhere to the linter, ultimately though!

**Comment by BillyFigueroa** [comment]
> @BillyFigueroa worth mentioning that precommit hook will be clientside only and I dont think it gets committed with the repo. I was experimenting with this a while back to prevent direct commits to specific branches with another repo and ended up adding a folder called hooks with the precommit hook there, and then adding a makefile that set up the hooks for people. That being said, people have to opt into it, which is fine, but I wouldn't assume everyone will use it.
> 
> On that note, I probably won't. I'm a regularly committer (hence my favor of squashing commits 😃). If I have to wait for a lint everytime I commit, that'll likely slow me down tremendously, haha. I will still adhere to the linter, ultimately though!

Thanks for that insight Brad. What do you recommend then we do for people not using VSCode?

**Comment by BillyFigueroa** [comment]
> Can we add a section in the README under linters about our use of eslint?

What exactly should I add regarding use? that we are using airbnb etc? that sort of stuff?

**Comment by BillyFigueroa** [comment]
@bradcypert I added a way to run prettier command line by using `lint:format` and then added some more information in the `README.MD` and made some quick updates to `yarn` commands because, unlike `NPM` we don't need

**Review by bradcypert — APPROVED** [review]

**Pull request closed without merging**
