### PR TITLE
Update node in matrix

### PR DESCRIPTION
**Pull request by saralohr**

### CODE REVIEW

**Comment by saralohr** [comment]
Wasn't sure if 10 and 12 should also have been removed @ryanwi.

**Comment by ryanwi** [comment]
I'll defer to the Triple B's on that one for final decision. Since we're no longer concerned about dugout, the 10 and 12 may not be needed?  Only need to be concerned about local builds and netlify at this point.

**Comment by bradjteamsnap** [comment]
Is it not supposed to work on anything below 14 now? because the way I understand it is that github will build and run the tests on each of the node versions in that matrix. So if 10 and 12 would fail the it would just lead to failed CI tests if we leave those in, but the tests seem to be passing now (at least the ci ones)

**Comment by saralohr** [comment]
It will probably work on versions below 14. We ran into an issue when Bacon was on 16.

**Comment by bradjteamsnap** [comment]
Ah gotcha, I'd say leave them in bc it's not failing any tests. But could go either way. Looks like Netlify is on 14.7.0. BTW thanks for adding the nvmrc!

**Review by bradjteamsnap — APPROVED** [review]

**Comment by saralohr** [comment]
Okay I'll leave them in for now. Bacon updated Netlify when it was failing the build with the version update. Team effort!

**Comment by ryanwi** [comment]
before, when having to deploy with dugout, this was constrained because dugout was running node 8 or something. I believe it's no longer constrained, so as long as everything works well on 14, that seems like it's enough if it works there.

**Pull request merged**
