### PR TITLE
Adding archive option to component

### PR DESCRIPTION
**Pull request by BillyFigueroa**
Adding the archive option to the component to be able to display archived seasons

Screen Shot 2021-06-14 at 10 28 00 AM

### CODE REVIEW

**Review by bradcypert — COMMENTED** [review]
What are your thoughts on finding a way to do this where it's more flexible (probably using some form of composition?). So far, this ToggleCheckboxList component has been very abstract, but now it's starting to become specific to seasons.

**Comment by BillyFigueroa** [comment]
> What are your thoughts on finding a way to do this where it's more flexible (probably using some form of composition?). So far, this ToggleCheckboxList component has been very abstract, but now it's starting to become specific to seasons.

yea, I def felt a little dirty adding this. Do you have anything in mind? I think we can push this through and think about a solution to change this

**Comment by bradcypert** [comment]
I'd really rather not push this through as is.  The `isArchived` flag doesn't really make sense outside of the scope of this one component use-case (so it's no longer generic) and TeamSnap UI is open source (and used by a few other people). It doesn't make sense for us to add a proprietary configuration for a component that's intended to be generic and for use everywhere.

It may be enough to pass in a list of tag components for additional tags.

```
 {
            "heading": "Micron Program 2",
            "subHeadings": [<Tag text=""2021 Summer Season"/>, <Tag icon="archived" text="Archived" />],
            "rows": []
}
```

What are your thoughts on this interface?

**Comment by BillyFigueroa** [comment]
@bradcypert forgot this is open source. You are right.

I like an array or a function that returns something there. I ll look into both

**Review by bradcypert — APPROVED** [review]

**Pull request merged**
