### PR TITLE
Table Component Updates

### PR DESCRIPTION
**Pull request by mikereinmiller**
Updates the table component to receive new props.

### CODE REVIEW

**Comment by amberwebb** [comment]
@mikereinmiller What happens in `componentWillRecieveProps` if you do not compare this.props and nextProps? Won't this component update even if there are no changes without the comparison?

I used `componentDidUpdate` in my PR because of the recommendation here https://reactjs.org/docs/react-component.html#unsafe_componentwillreceiveprops

**Comment by amberwebb** [comment]
When is it appropriate to use `componentDidUpdate` vs `componentWillReceiveProps`?

Even though the new lifecycle methods would cause issues in some of our apps on older versions of React, we need to think about moving away from `Will` methods since React is deprecating them. The `Did` methods are available in older versions of React. This is a conversation we should have as a Guild. It will be time consuming to go through each component and update deprecated methods, especially since we have no tests (hoping we will by that point).

But, I linked this into my Hydra branch and filtering is working as expected. Sorting is still buggy. Perhaps it's my implementation of the Table component.

**Comment by mikereinmiller** [comment]
It's not really a matter of 'not updating'.  We will definitely be updating.  But these are soon going to be marked as deprecated and then in another future release they will be removed.  We aren't even to the version of getting the deprecated warnings yet.  So we have time to migrate the appropriate applications over as well as all of teamsnap-ui.  LFE is still using both the toolkit and UI components. We will be updating LFE hopefully soon or just moving it to hydra altogether.  So I think for now in the short term, it is a little early to change.  We can change all of UI at the same time, when we migrate some of the apps that are depending on these early releases still.

**Comment by mikereinmiller** [comment]
@amberwebb I think those changes for max height look good!  I say have @Ollo double check over the recent changes and if he gives a 👍 we should be good.

**Pull request merged**
